### ISSUE TITLE
Determine a unique name for `raven` and publish on conda-forge

### ISSUE THREAD

**Issue by Zeitsperre** [CSHS-CWRA/raven-feedstock#8]
`raven` appears to be a popular name for `sentry`-related libraries (see [conda-forge](https://anaconda.org/search?q=raven)). We would need a unique name so that installing the `raven` model doesn't accidentally pull one of these other libraries instead.

Proposal: `raven-hydro`

**Comment by cjauvin** [comment]
:+1: for `raven-hydro`

**Comment by julemai** [comment]
`RavenHydro` sounds good to me. 

That's also our Twitter handle:
https://twitter.com/RavenHydro

**Comment by Zeitsperre** [comment]
Relevant PRs:
- https://github.com/conda-forge/staged-recipes/pull/14680
- https://github.com/conda-forge/staged-recipes/pull/14684

**Comment by Zeitsperre** [comment]
Closed with https://github.com/conda-forge/raven-hydro-feedstock
